### PR TITLE
Django 2.0 compatibility

### PR DESCRIPTION
**Pull request by wesleykendall**
@wesokes @jaredlewis I don't think there is anything else needed for Django 2.0 compatibility in this package, but I'll check out the tests if they fail

### CODE REVIEW

**Comment by wesokes** [comment]
@wesleykendall i added 2.0 support and removed py27 https://github.com/ambitioninc/django-db-mutex/pull/53

**Comment by JioHooney** [comment]
are you removed py27? 
does python2.7 support end?

**Comment by wesokes** [comment]
@JioHooney version 1.0.0 adds support for django 2.0 which is python 3 only. We still test against django 1.11 and even though python 2.7 is no longer tested in this release, it should still work with 1.11. If you want to keep using this project with older versions of python and django, you can pin your version to 0.5.0.

**Comment by JioHooney** [comment]
@wesokes  I appreciate that.

**Pull request closed without merging**
